CREATE DATABASE cricket_db;
use cricket_db;


CREATE TABLE TEAM(TEAM_DB_ID INT PRIMARY KEY AUTO_INCREMENT, TEAM_CODE VARCHAR(3) NOT NULL, TEAM_NAME VARCHAR(100) NOT NULL, CONSTRAINT UC_TEAM UNIQUE(TEAM_CODE,TEAM_NAME));
CREATE TABLE PLAYER(PLAYER_DB_ID INT PRIMARY KEY AUTO_INCREMENT, TEAM_DB_ID INT NOT NULL, PLAYER_NAME VARCHAR(100) NOT NULL,  FOREIGN KEY(TEAM_DB_ID) REFERENCES TEAM(TEAM_DB_ID), CONSTRAINT UC_PLAYER UNIQUE(PLAYER_NAME,TEAM_DB_ID));
CREATE TABLE MATCHS(MATCHS_DB_ID INT PRIMARY KEY AUTO_INCREMENT, TEAM1_DB_ID INT NOT NULL, TEAM2_DB_ID INT NOT NULL,FOREIGN KEY(TEAM1_DB_ID) REFERENCES TEAM(TEAM_DB_ID),FOREIGN KEY(TEAM2_DB_ID) REFERENCES TEAM(TEAM_DB_ID));
CREATE TABLE MATCHS_SUMMARY(MATCHS_SUMMARY_DB_ID INT PRIMARY KEY AUTO_INCREMENT, MATCHS_DB_ID INT NOT NULL, TEAM_DB_ID INT NOT NULL, PLAYER_DB_ID INT, SCORE INT NOT NULL, BALLS_CONSUMED INT NOT NULL, FOREIGN KEY(MATCHS_DB_ID) REFERENCES MATCHS(MATCHS_DB_ID),FOREIGN KEY(TEAM_DB_ID) REFERENCES TEAM(TEAM_DB_ID));
INSERT INTO TEAM(TEAM_CODE,TEAM_NAME) VALUES('IND','INDIA');
INSERT INTO TEAM(TEAM_CODE,TEAM_NAME) VALUES('PAK','PAKISTAN');

INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'IND'),'R Sharma');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'IND'),'S Gill');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'IND'),'V Kohli');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'IND'),'KL Rahul');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'IND'),'S Iyer');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'IND'),'H Pandya');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'IND'),'R Jadeja');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'IND'),'R Ashwin');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'IND'),'J Bumrah');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'IND'),'M Siraj');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'IND'),'K Yadav');

INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'PAK'),'A Shafique');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'PAK'),'I Haq');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'PAK'),'B Azam');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'PAK'),'M Rizwan');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'PAK'),'S Shakeel');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'PAK'),'I Ahmed');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'PAK'),'S Khan');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'PAK'),'M Nawaz');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'PAK'),'H Ali');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'PAK'),'S Afridi');
INSERT INTO PLAYER(TEAM_DB_ID,PLAYER_NAME) VALUES((SELECT TEAM_DB_ID FROM TEAM WHERE TEAM_CODE = 'PAK'),'H Rauf');



